<div class="row g-3">
    <div class="col-md-4"><label class="form-label" for="vehicle_id">Vehicle ID</label><input id="vehicle_id" name="vehicle_id" type="number" value="{{ old('vehicle_id', $record->vehicle_id ?? '') }}" class="form-control @error('vehicle_id') is-invalid @enderror">@error('vehicle_id')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
    <div class="col-md-4"><label class="form-label" for="driver_id">Driver ID</label><input id="driver_id" name="driver_id" type="number" value="{{ old('driver_id', $record->driver_id ?? '') }}" class="form-control @error('driver_id') is-invalid @enderror">@error('driver_id')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
    <div class="col-md-4"><label class="form-label" for="status">Status</label><select id="status" name="status" class="form-select @error('status') is-invalid @enderror">@foreach(['Unpaid','Paid','Disputed','Cancelled'] as $status)<option value="{{ $status }}" @selected(old('status', $record->status ?? 'Unpaid')===$status)>{{ $status }}</option>@endforeach</select>@error('status')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
    <div class="col-md-4"><label class="form-label" for="challan_no">Challan No</label><input id="challan_no" name="challan_no" value="{{ old('challan_no', $record->challan_no ?? '') }}" class="form-control @error('challan_no') is-invalid @enderror">@error('challan_no')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
    <div class="col-md-4"><label class="form-label" for="violation_type">Violation Type</label><input id="violation_type" name="violation_type" value="{{ old('violation_type', $record->violation_type ?? '') }}" class="form-control @error('violation_type') is-invalid @enderror">@error('violation_type')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
    <div class="col-md-4"><label class="form-label" for="challan_date">Challan Date</label><input id="challan_date" name="challan_date" type="date" value="{{ old('challan_date', optional($record->challan_date ?? null)->format('Y-m-d')) }}" class="form-control @error('challan_date') is-invalid @enderror">@error('challan_date')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
    <div class="col-md-4"><label class="form-label" for="amount">Amount</label><input id="amount" name="amount" type="number" step="0.01" value="{{ old('amount', $record->amount ?? 0) }}" class="form-control @error('amount') is-invalid @enderror">@error('amount')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
</div>
<div class="mt-3"><button class="btn btn-primary" type="submit">Save</button><a class="btn btn-light" href="{{ route('admin.fleet.challans.index') }}">Cancel</a></div>
