@extends('layouts.app')
@section('title','Statement')
@section('page_title','Statement')
@push('styles')
<style>@media print {.no-print{display:none!important;} body{background:#fff;} .card{border:0;box-shadow:none!important;}}</style>
@endpush
@section('content')
<div class="card shadow-sm mb-3 no-print"><div class="card-body"><form method="GET" class="row g-2 align-items-end"><div class="col-md-4"><label class="form-label">Member</label><select name="member_id" class="form-select"><option value="">All</option>@foreach($members as $m)<option value="{{ $m->id }}" @selected((string)$memberId===(string)$m->id)>{{ $m->member_code }} - {{ $m->name }}</option>@endforeach</select></div><div class="col-md-2"><label class="form-label">Month</label><input name="month_cycle" class="form-control" value="{{ $monthCycle }}" placeholder="2026-03"></div><div class="col-md-2"><label class="form-label">From</label><input name="from_month" class="form-control" value="{{ $fromMonth }}" placeholder="2026-01"></div><div class="col-md-2"><label class="form-label">To</label><input name="to_month" class="form-control" value="{{ $toMonth }}" placeholder="2026-03"></div><div class="col-md-2 d-flex gap-2"><button class="btn btn-outline-primary">Load</button><button type="button" onclick="window.print()" class="btn btn-primary">Print</button></div></form></div></div>
<div class="card shadow-sm"><div class="card-header">Statement Rows</div><div class="card-body table-responsive"><table class="table table-sm align-middle"><thead><tr><th>Date</th><th>Month</th><th>Member</th><th>Ref</th><th>Debit</th><th>Credit</th><th>Signed</th><th>Balance</th></tr></thead><tbody>@foreach($rows as $r)<tr><td>{{ optional($r['date'])->format('Y-m-d') }}</td><td>{{ $r['month_cycle'] }}</td><td>{{ $r['member_code'] }}</td><td>{{ $r['ref_type'] }}#{{ $r['ref_id'] }}</td><td>{{ number_format((float)$r['debit'],2) }}</td><td>{{ number_format((float)$r['credit'],2) }}</td><td>{{ number_format((float)$r['signed_amount'],2) }}</td><td>{{ number_format((float)$r['balance_after'],2) }}</td></tr>@endforeach</tbody></table></div></div>
@endsection
