<div class="row g-3">
    <div class="col-md-4"><label class="form-label" for="vehicle_id">Vehicle ID</label><input id="vehicle_id" name="vehicle_id" type="number" value="{{ old('vehicle_id', $record->vehicle_id ?? '') }}" class="form-control @error('vehicle_id') is-invalid @enderror">@error('vehicle_id')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
    <div class="col-md-4"><label class="form-label" for="item_type">Item Type</label><select id="item_type" name="item_type" class="form-select @error('item_type') is-invalid @enderror"><option value="">Select</option>@foreach(['tyre'=>'Tyre','battery'=>'Battery'] as $value=>$label)<option value="{{ $value }}" @selected(old('item_type', $record->item_type ?? '')===$value)>{{ $label }}</option>@endforeach</select>@error('item_type')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
    <div class="col-md-4"><label class="form-label" for="status">Status</label><select id="status" name="status" class="form-select @error('status') is-invalid @enderror">@foreach(['Active','Removed','Failed','Warranty Claim'] as $status)<option value="{{ $status }}" @selected(old('status', $record->status ?? 'Active')===$status)>{{ $status }}</option>@endforeach</select>@error('status')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
    <div class="col-md-4"><label class="form-label" for="brand">Brand</label><input id="brand" name="brand" value="{{ old('brand', $record->brand ?? '') }}" class="form-control @error('brand') is-invalid @enderror">@error('brand')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
    <div class="col-md-4"><label class="form-label" for="serial_no">Serial No</label><input id="serial_no" name="serial_no" value="{{ old('serial_no', $record->serial_no ?? '') }}" class="form-control @error('serial_no') is-invalid @enderror">@error('serial_no')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
    <div class="col-md-4"><label class="form-label" for="cost">Cost</label><input id="cost" name="cost" type="number" step="0.01" value="{{ old('cost', $record->cost ?? 0) }}" class="form-control @error('cost') is-invalid @enderror">@error('cost')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
    <div class="col-md-3"><label class="form-label" for="installed_at">Installed Date</label><input id="installed_at" name="installed_at" type="date" value="{{ old('installed_at', optional($record->installed_at ?? null)->format('Y-m-d')) }}" class="form-control @error('installed_at') is-invalid @enderror">@error('installed_at')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
    <div class="col-md-3"><label class="form-label" for="installed_odometer">Installed Odometer</label><input id="installed_odometer" name="installed_odometer" type="number" step="0.01" value="{{ old('installed_odometer', $record->installed_odometer ?? '') }}" class="form-control @error('installed_odometer') is-invalid @enderror">@error('installed_odometer')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
    <div class="col-md-3"><label class="form-label" for="removed_at">Removed Date</label><input id="removed_at" name="removed_at" type="date" value="{{ old('removed_at', optional($record->removed_at ?? null)->format('Y-m-d')) }}" class="form-control @error('removed_at') is-invalid @enderror">@error('removed_at')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
    <div class="col-md-3"><label class="form-label" for="removed_odometer">Removed Odometer</label><input id="removed_odometer" name="removed_odometer" type="number" step="0.01" value="{{ old('removed_odometer', $record->removed_odometer ?? '') }}" class="form-control @error('removed_odometer') is-invalid @enderror">@error('removed_odometer')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
</div>
<div class="mt-3"><button class="btn btn-primary" type="submit">Save</button><a class="btn btn-light" href="{{ route('admin.fleet.tyres-batteries.index') }}">Cancel</a></div>
